import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const dbUrl = process.env.DIRECT_URL || process.env.DATABASE_URL;
const prisma = new PrismaClient({
  datasources: { db: { url: dbUrl } },
});

async function main() {
  console.log('[SEEDER] Initializing TaniCo database seeder...');

  // 1. ROLES
  console.log('[SEEDER] 1. Seeding roles...');
  const superAdminRole = await prisma.role.upsert({
    where: { name: 'SUPER_ADMIN' },
    update: {},
    create: { name: 'SUPER_ADMIN' },
  });

  await prisma.role.upsert({
    where: { name: 'ADMIN' },
    update: {},
    create: { name: 'ADMIN' },
  });

  await prisma.role.upsert({
    where: { name: 'CUSTOMER' },
    update: {},
    create: { name: 'CUSTOMER' },
  });

  // 2. ADMIN USER & ADMIN PROFILE
  console.log('[SEEDER] 2. Seeding super admin account (admin@tanico.id)...');
  const plainPassword = 'Admin123!';
  const hashedPassword = await bcrypt.hash(plainPassword, 12);

  await prisma.user.upsert({
    where: { email: 'admin@tanico.id' },
    update: {
      name: 'Administrator TaniCo',
      password: hashedPassword,
      status: 'ACTIVE',
      roleId: superAdminRole.id,
      avatar: '',
      provider: 'Email',
    },
    create: {
      email: 'admin@tanico.id',
      name: 'Administrator TaniCo',
      password: hashedPassword,
      status: 'ACTIVE',
      roleId: superAdminRole.id,
      avatar: '',
      provider: 'Email',
    },
  });

  await prisma.adminProfile.upsert({
    where: { id: 'default' },
    update: {
      name: 'Administrator TaniCo',
      email: 'admin@tanico.id',
      role: 'SUPER_ADMIN',
      avatar: '',
    },
    create: {
      id: 'default',
      name: 'Administrator TaniCo',
      email: 'admin@tanico.id',
      role: 'SUPER_ADMIN',
      avatar: '',
    },
  });

  // 3. FARMER LOCATIONS
  console.log('[SEEDER] 3. Seeding master metadata (farmer locations)...');
  const farmerLocations = [
    'Pemali, Kabupaten Bangka',
    'Sungailiat, Kabupaten Bangka',
    'Merawang, Kabupaten Bangka',
    'Pangkalpinang, Bangka',
    'Belinyu, Kabupaten Bangka',
    'Koba, Bangka Tengah',
  ];
  const createdLocations = {};
  for (const locName of farmerLocations) {
    const loc = await prisma.farmerLocation.upsert({
      where: { name: locName },
      update: {},
      create: { name: locName },
    });
    createdLocations[locName] = loc.id;
  }

  const benefitsList = [
    '100% Bebas Pestisida Kimia',
    'Dipetik Fajar Hari',
    'Pengiriman Hari Yang Sama',
    'Mitra Petani Lokal Bangka',
    'Kemasan Eco-Friendly',
    'Garansi Kesegaran 100%',
  ];

  // 4. CATEGORIES (6 categories)
  console.log('[SEEDER] 4. Seeding categories (6 categories)...');
  const categoriesData = [
    {
      name: 'Sayuran Daun',
      slug: 'sayuran-daun',
      description: 'Sayuran hijau segar kaya serat, klorofil, dan vitamin A. Dipetik fajar setiap hari dari kebun mitra Bangka.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 1,
      badgeText: 'Terlaris',
      badgeColor: 'Green',
      showOnHomepage: true,
      ctaText: 'Lihat Sayuran Daun',
      ctaLink: '/produk?kategori=Sayuran+Daun',
    },
    {
      name: 'Sayuran Buah',
      slug: 'sayuran-buah',
      description: 'Tomat, cabai, terung, buncis, dan timun segar penuh nutrisi dari kebun hidroponik & organik pilihan.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 2,
      badgeText: 'Segar Alami',
      badgeColor: 'Emerald',
      showOnHomepage: true,
      ctaText: 'Lihat Sayuran Buah',
      ctaLink: '/produk?kategori=Sayuran+Buah',
    },
    {
      name: 'Sayuran Umbi & Akar',
      slug: 'sayuran-umbi',
      description: 'Wortel, kentang, bit, dan umbi-umbian sehat bebas bahan kimia sintetis.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 3,
      badgeText: 'Organik',
      badgeColor: 'Amber',
      showOnHomepage: true,
      ctaText: 'Lihat Umbi & Akar',
      ctaLink: '/produk?kategori=Sayuran+Umbi',
    },
    {
      name: 'Herbal & Rempah',
      slug: 'herbal-rempah',
      description: 'Rempah-rempah tradisional, daun mint, dan tanaman herbal berkhasiat tinggi untuk kesehatan harian.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 4,
      badgeText: 'Aroma Fresh',
      badgeColor: 'Teal',
      showOnHomepage: true,
      ctaText: 'Lihat Rempah',
      ctaLink: '/produk?kategori=Herbal+%26+Rempah',
    },
    {
      name: 'Jamur & Sprouts',
      slug: 'jamur-sprouts',
      description: 'Jamur tiram segar dan kecambah hidroponik kaya protein nabati dan antioksidan.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 5,
      badgeText: 'Tinggi Protein',
      badgeColor: 'Purple',
      showOnHomepage: true,
      ctaText: 'Lihat Jamur',
      ctaLink: '/produk?kategori=Jamur+%26+Sprouts',
    },
    {
      name: 'Paket Hemat & Bundel',
      slug: 'paket-hemat',
      description: 'Paket kombinasi sayur mingguan keluarga hemat, praktis, dan lengkap dengan pilihan gizi seimbang.',
      image: '',
      heroImage: '',
      banner: '',
      ogImage: '',
      status: 'Aktif',
      sortOrder: 6,
      badgeText: 'Hemat 15%',
      badgeColor: 'Rose',
      showOnHomepage: true,
      ctaText: 'Lihat Paket Bundel',
      ctaLink: '/produk?kategori=Paket+Hemat+%26+Bundel',
    },
  ];

  const createdCategories = {};
  for (const catData of categoriesData) {
    const cat = await prisma.category.upsert({
      where: { slug: catData.slug },
      update: catData,
      create: catData,
    });
    createdCategories[catData.name] = cat.id;
  }

  // 5. PRODUCTS (30 products)
  console.log('[SEEDER] 5. Seeding products (30 organic & hydroponic products)...');
  const productsData = [
    {
      name: 'Bayam Hijau Organik',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 10000,
      discountPrice: 8500,
      unit: '250 gram',
      image: '',
      stock: 50,
      rating: 4.9,
      description: 'Bayam hijau segar kaya zat besi dan antioksidan alami. Ditanam tanpa pestisida kimia di kebun organik Sungailiat, dipetik subuh sebelum dikirim.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: 'Bebas Kimia Sintetis',
      weight: 250,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 140,
    },
    {
      name: 'Bayam Merah Organik',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 12000,
      discountPrice: 10000,
      unit: '250 gram',
      image: '',
      stock: 40,
      rating: 5.0,
      description: 'Bayam merah kaya antosianin dan zat besi tinggi. Memiliki rasa manis alami yang lembut, sangat direkomendasikan untuk kesehatan darah dan MPASI anak.',
      origin: 'Kebun Merawang, Bangka',
      certification: 'Sertifikat Organik Lokal',
      weight: 250,
      isFeatured: true,
      isPopular: true,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Merawang, Kabupaten Bangka'],
      soldCount: 95,
    },
    {
      name: 'Kangkung Hidroponik Segar',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 12000,
      discountPrice: 10000,
      unit: '250 gram',
      image: '',
      stock: 60,
      rating: 5.0,
      description: 'Kangkung hidroponik berbatang renyah dan daun hijau segar tanpa getah pahit. Ditanam dengan aliran air bernutrisi higienis bebas pencemaran tanah.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Sertifikat Hidroponik Clean Harvest',
      weight: 250,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 210,
    },
    {
      name: 'Selada Keriting Hijau',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 18000,
      discountPrice: 16000,
      unit: '200 gram',
      image: '',
      stock: 35,
      rating: 4.9,
      description: 'Selada keriting hijau manis dan renyah alami. Sangat cocok dijadikan bahan utama salad segar harian, isian burger, maupun lalapan sehat.',
      origin: 'Kebun Pemali, Bangka',
      certification: '100% Bebas Pestisida',
      weight: 200,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 175,
    },
    {
      name: 'Selada Romaine Hidroponik',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 22000,
      discountPrice: 19000,
      unit: '250 gram',
      image: '',
      stock: 30,
      rating: 4.8,
      description: 'Selada Romaine berdaun tebal dan kokoh dengan tekstur super renyah. Pilihan favorit resto dan keluarga untuk sajian Caesar Salad premium.',
      origin: 'Kebun Pangkalpinang, Bangka',
      certification: 'Hidroponik Standar Resto',
      weight: 250,
      isFeatured: false,
      isPopular: true,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pangkalpinang, Bangka'],
      soldCount: 88,
    },
    {
      name: 'Pakcoy Hijau Hidroponik',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 15000,
      discountPrice: 13000,
      unit: '300 gram',
      image: '',
      stock: 45,
      rating: 4.9,
      description: 'Pakcoy atau sawi daging dengan kelopak tebal, juicy, dan manis. Sangat nikmat ditumis dengan bawang putih atau dicampur ke dalam mie rebus sehat.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Sertifikat Clean Harvest',
      weight: 300,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 160,
    },
    {
      name: 'Sawi Pahit Organik',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 11000,
      discountPrice: null,
      unit: '250 gram',
      image: '',
      stock: 25,
      rating: 4.7,
      description: 'Sawi pahit atau pahit-pahit segar kaya antioksidan dan enzim alami. Sangat cocok diproses menjadi masakan sup sehat berkaldu gurih.',
      origin: 'Kebun Belinyu, Bangka',
      certification: 'Organik Alami',
      weight: 250,
      isFeatured: false,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Belinyu, Kabupaten Bangka'],
      soldCount: 45,
    },
    {
      name: 'Sawi Hijau Caisim',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 10000,
      discountPrice: 8500,
      unit: '300 gram',
      image: '',
      stock: 50,
      rating: 4.8,
      description: 'Caisim atau sawi bakso segar berdaun lebat dan batang lembut. Hasil panen lokal yang bebas residu bahan kimia sintetis.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: 'Bebas Pestisida Kimia',
      weight: 300,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 130,
    },
    {
      name: 'Kailan Hidroponik Crisp',
      categoryName: 'Sayuran Daun',
      categoryId: createdCategories['Sayuran Daun'],
      price: 20000,
      discountPrice: 17500,
      unit: '200 gram',
      image: '',
      stock: 20,
      rating: 4.9,
      description: 'Kailan muda hidroponik bertekstur lembut dan manis renyah. Pilihan tepat untuk tumisan kailan saus tiram khas oriental.',
      origin: 'Kebun Pangkalpinang, Bangka',
      certification: 'Hidroponik Clean Harvest',
      weight: 200,
      isFeatured: true,
      isPopular: false,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pangkalpinang, Bangka'],
      soldCount: 70,
    },
    {
      name: 'Brokoli Organik Segar',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 25000,
      discountPrice: 22000,
      unit: '300 gram',
      image: '',
      stock: 30,
      rating: 5.0,
      description: 'Brokoli hijau padat kaya sulforafan dan serat tinggi. Bebas dari ulat dan bahan kimia, aman langsung dikonsumsi setelah dikukus sebentar.',
      origin: 'Kebun Merawang, Bangka',
      certification: '100% Organik Murni',
      weight: 300,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Merawang, Kabupaten Bangka'],
      soldCount: 185,
    },
    {
      name: 'Kembang Kol Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 24000,
      discountPrice: 21000,
      unit: '350 gram',
      image: '',
      stock: 25,
      rating: 4.8,
      description: 'Kembang kol putih bersih dan padat. Memiliki cita rasa gurih renyah alami, cocok untuk tumisan capcay atau olahan kol goreng sehat.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: 'Bebas Pestisida',
      weight: 350,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 110,
    },
    {
      name: 'Kubis Kol Putih Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 14000,
      discountPrice: 12000,
      unit: '500 gram',
      image: '',
      stock: 40,
      rating: 4.7,
      description: 'Kubis putih renyah dengan daun tebal segar. Ditanam secara organik tanpa pestisida berbahaya, dipanen segar setiap pagi.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Bebas Kimia Sintetis',
      weight: 500,
      isFeatured: false,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 90,
    },
    {
      name: 'Kubis Ungu Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 26000,
      discountPrice: 23000,
      unit: '400 gram',
      image: '',
      stock: 20,
      rating: 4.9,
      description: 'Kubis ungu cantik bermutu tinggi kaya anthocyanin dan vitamin C. Sangat cocok dijadikan pewarna alami salad dan sajian olahan sehat.',
      origin: 'Kebun Merawang, Bangka',
      certification: 'Organik Bangka',
      weight: 400,
      isFeatured: true,
      isPopular: false,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Merawang, Kabupaten Bangka'],
      soldCount: 65,
    },
    {
      name: 'Tomat Cherry Red Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 22000,
      discountPrice: 19500,
      unit: '250 gram',
      image: '',
      stock: 35,
      rating: 4.9,
      description: 'Tomat cherry merah ranum dan manis segar penuh likopen alami. Cocok dijadikan camilan sehat anak maupun campuran salad harian.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Organik Murni',
      weight: 250,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 155,
    },
    {
      name: 'Tomat Buah Segar Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 16000,
      discountPrice: 14000,
      unit: '500 gram',
      image: '',
      stock: 45,
      rating: 4.8,
      description: 'Tomat buah besar dengan daging tebal dan kadar air melimpah. Bebas bahan kimia pematang sintetis, masak pohon alami.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: 'Masak Pohon Alami',
      weight: 500,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 125,
    },
    {
      name: 'Wortel Baby Organik',
      categoryName: 'Sayuran Umbi & Akar',
      categoryId: createdCategories['Sayuran Umbi & Akar'],
      price: 20000,
      discountPrice: 18000,
      unit: '300 gram',
      image: '',
      stock: 50,
      rating: 4.9,
      description: 'Wortel baby manis bertekstur empuk renyah tanpa rasa langu. Kaya beta-karoten, sangat aman untuk camilan langsung dan jus sehat.',
      origin: 'Kebun Pemali, Bangka',
      certification: '100% Organik Murni',
      weight: 300,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 190,
    },
    {
      name: 'Cabai Rawit Merah Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 28000,
      discountPrice: 25000,
      unit: '200 gram',
      image: '',
      stock: 30,
      rating: 4.9,
      description: 'Cabai rawit merah pedas mantap dipetik langsung segar dari pohon. Bebas pestisida racun, memberikan sensasi pedas murni alami.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: 'Panen Alami Segar',
      weight: 200,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 220,
    },
    {
      name: 'Cabai Merah Keriting',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 24000,
      discountPrice: 21000,
      unit: '250 gram',
      image: '',
      stock: 35,
      rating: 4.8,
      description: 'Cabai merah keriting segar merah merona, cocok untuk membuat aneka sambal Nusantara dan bumbu balado khas Bangka.',
      origin: 'Kebun Koba, Bangka Tengah',
      certification: 'Bebas Pestisida Kimia',
      weight: 250,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Koba, Bangka Tengah'],
      soldCount: 145,
    },
    {
      name: 'Terong Ungu Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 13000,
      discountPrice: 11000,
      unit: '500 gram',
      image: '',
      stock: 40,
      rating: 4.8,
      description: 'Terong ungu segar berukuran mulus dan daging empuk manis. Bebas obat serangga kimia sintetis.',
      origin: 'Kebun Merawang, Bangka',
      certification: 'Bebas Kimia Sintetis',
      weight: 500,
      isFeatured: false,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Merawang, Kabupaten Bangka'],
      soldCount: 80,
    },
    {
      name: 'Buncis Organik Renyah',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 15000,
      discountPrice: 13000,
      unit: '250 gram',
      image: '',
      stock: 35,
      rating: 4.8,
      description: 'Buncis muda renyah manis tanpa serat kasar. Dipanen saat umur optimal sehingga teksturnya sangat empuk saat ditumis.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Sertifikat Organik Alami',
      weight: 250,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 115,
    },
    {
      name: 'Mentimun Hidroponik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 12000,
      discountPrice: 10000,
      unit: '500 gram',
      image: '',
      stock: 45,
      rating: 4.9,
      description: 'Mentimun hidroponik tanpa pahit, kaya kandungan air dan mineral esensial. Sangat cocok untuk jus peluntur lemak atau lalapan segar.',
      origin: 'Kebun Pangkalpinang, Bangka',
      certification: 'Hidroponik Clean Harvest',
      weight: 500,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pangkalpinang, Bangka'],
      soldCount: 135,
    },
    {
      name: 'Jagung Manis Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 16000,
      discountPrice: 14000,
      unit: '2 Tongkol',
      image: '',
      stock: 30,
      rating: 4.9,
      description: 'Jagung manis organik bulir kuning rapat penuh air manis alami. Ditanam tanpa pupuk kimia berat, nikmat direbus maupun dibakar.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: '100% Organik Murni',
      weight: 600,
      isFeatured: true,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 105,
    },
    {
      name: 'Daun Bawang Segar',
      categoryName: 'Herbal & Rempah',
      categoryId: createdCategories['Herbal & Rempah'],
      price: 8000,
      discountPrice: null,
      unit: '150 gram',
      image: '',
      stock: 50,
      rating: 4.8,
      description: 'Daun bawang berbatang putih tebal dan daun hijau harum. Memberikan aroma masakan khas yang menyegarkan pada hidangan sup dan telur.',
      origin: 'Kebun Pemali, Bangka',
      certification: 'Bebas Pestisida',
      weight: 150,
      isFeatured: false,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 170,
    },
    {
      name: 'Seledri Hidroponik',
      categoryName: 'Herbal & Rempah',
      categoryId: createdCategories['Herbal & Rempah'],
      price: 10000,
      discountPrice: 8500,
      unit: '100 gram',
      image: '',
      stock: 40,
      rating: 4.9,
      description: 'Seledri hidroponik dengan aroma wangi tajam dan tangkai tebal renyah. Sangat bagus untuk campuran jus penurunan darah tinggi.',
      origin: 'Kebun Pangkalpinang, Bangka',
      certification: 'Hidroponik Clean Harvest',
      weight: 100,
      isFeatured: false,
      isPopular: false,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pangkalpinang, Bangka'],
      soldCount: 95,
    },
    {
      name: 'Labu Siam Organik',
      categoryName: 'Sayuran Buah',
      categoryId: createdCategories['Sayuran Buah'],
      price: 11000,
      discountPrice: 9500,
      unit: '500 gram',
      image: '',
      stock: 35,
      rating: 4.7,
      description: 'Labu siam muda getah minim bertekstur empuk manis. Pilihan tradisional sehat untuk lodeh maupun rebusan lalapan.',
      origin: 'Kebun Belinyu, Bangka',
      certification: 'Organik Alami',
      weight: 500,
      isFeatured: false,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Belinyu, Kabupaten Bangka'],
      soldCount: 60,
    },
    {
      name: 'Lobak Putih Organik',
      categoryName: 'Sayuran Umbi & Akar',
      categoryId: createdCategories['Sayuran Umbi & Akar'],
      price: 15000,
      discountPrice: 13000,
      unit: '400 gram',
      image: '',
      stock: 25,
      rating: 4.8,
      description: 'Lobak putih mulus tanpa bahan pemutih atau obat pengawet. Kaya enzim pencernaan dan baik untuk kesehatan paru-paru.',
      origin: 'Kebun Merawang, Bangka',
      certification: 'Organik Bangka',
      weight: 400,
      isFeatured: false,
      isPopular: false,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Merawang, Kabupaten Bangka'],
      soldCount: 50,
    },
    {
      name: 'Bit Merah Organik',
      categoryName: 'Sayuran Umbi & Akar',
      categoryId: createdCategories['Sayuran Umbi & Akar'],
      price: 25000,
      discountPrice: 22000,
      unit: '300 gram',
      image: '',
      stock: 20,
      rating: 4.9,
      description: 'Umbi bit merah super segar kaya nitrat alami penambah stamina dan hemoglobin darah. Sangat baik untuk jus kesehatan harian.',
      origin: 'Kebun Sungailiat, Bangka',
      certification: '100% Organik Murni',
      weight: 300,
      isFeatured: true,
      isPopular: false,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Sungailiat, Kabupaten Bangka'],
      soldCount: 85,
    },
    {
      name: 'Jamur Tiram Putih Segar',
      categoryName: 'Jamur & Sprouts',
      categoryId: createdCategories['Jamur & Sprouts'],
      price: 14000,
      discountPrice: 12000,
      unit: '250 gram',
      image: '',
      stock: 35,
      rating: 4.9,
      description: 'Jamur tiram putih bersih dipanen dari kumbung bersuhu terkontrol. Daging tebal dan gurih, kaya beta-glukan penambah daya tahan tubuh.',
      origin: 'Mitra Kumbung Pemali, Bangka',
      certification: 'Budidaya Higienis',
      weight: 250,
      isFeatured: true,
      isPopular: true,
      isNew: false,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 160,
    },
    {
      name: 'Daun Mint Fresh Organik',
      categoryName: 'Herbal & Rempah',
      categoryId: createdCategories['Herbal & Rempah'],
      price: 12000,
      discountPrice: null,
      unit: '100 gram',
      image: '',
      stock: 30,
      rating: 5.0,
      description: 'Daun mint hijau segar beraroma menthol dingin kuat. Pilihan tepat untuk infusi air minum sehat, teh herbal, dan hiasan minuman.',
      origin: 'Kebun Pangkalpinang, Bangka',
      certification: 'Hidroponik Clean Harvest',
      weight: 100,
      isFeatured: false,
      isPopular: true,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pangkalpinang, Bangka'],
      soldCount: 110,
    },
    {
      name: 'Paket Sayur Sup Sehat Mingguan',
      categoryName: 'Paket Hemat & Bundel',
      categoryId: createdCategories['Paket Hemat & Bundel'],
      price: 45000,
      discountPrice: 38000,
      unit: '1 Paket (5 Jenis Sayur)',
      image: '',
      stock: 25,
      rating: 5.0,
      description: 'Paket lengkap hemat untuk memasak sup sehat keluarga: Wortel Baby, Kentang Organik, Buncis Muda, Seledri, dan Daun Bawang Segar.',
      origin: 'Mitra Kebun Bangka',
      certification: 'Paket Hemat Kombinasi Gizi',
      weight: 1200,
      isFeatured: true,
      isPopular: true,
      isNew: true,
      status: 'Aktif',
      farmerLocationId: createdLocations['Pemali, Kabupaten Bangka'],
      soldCount: 250,
    },
  ];

  const createdProductIds = [];
  for (const prodData of productsData) {
    const existing = await prisma.product.findFirst({ where: { name: prodData.name } });
    if (existing) {
      const updated = await prisma.product.update({ where: { id: existing.id }, data: prodData });
      createdProductIds.push(updated.id);
    } else {
      const created = await prisma.product.create({ data: prodData });
      createdProductIds.push(created.id);
    }
  }

  // 6. GALLERY (10 photos)
  console.log('[SEEDER] 6. Seeding gallery (10 photos)...');
  const galleryData = [
    { title: 'Kebun Hidroponik Pemali Bangka', image: '', span: 'col-span-1', sortOrder: 1, active: true },
    { title: 'Panen Subuh Sayur Bayam Organik', image: '', span: 'col-span-2', sortOrder: 2, active: true },
    { title: 'Proses Sortir & Quality Control TaniCo', image: '', span: 'col-span-1', sortOrder: 3, active: true },
    { title: 'Pengemasan Ramah Lingkungan Eco-Pack', image: '', span: 'col-span-1', sortOrder: 4, active: true },
    { title: 'Bibit Selada Unggulan Hydro-Farm', image: '', span: 'col-span-1', sortOrder: 5, active: true },
    { title: 'Penyiraman Otomatis Kebun Smart Farming', image: '', span: 'col-span-2', sortOrder: 6, active: true },
    { title: 'Kunjungan Komunitas Organik Bangka', image: '', span: 'col-span-1', sortOrder: 7, active: true },
    { title: 'Distribusi Segar Harian Pangkalpinang', image: '', span: 'col-span-1', sortOrder: 8, active: true },
    { title: 'Pemanenan Tomat Cherry Merah Ranum', image: '', span: 'col-span-1', sortOrder: 9, active: true },
    { title: 'Pelatihan Petani Muda Sungailiat', image: '', span: 'col-span-1', sortOrder: 10, active: true },
  ];

  for (const galData of galleryData) {
    const existing = await prisma.gallery.findFirst({ where: { title: galData.title } });
    if (existing) {
      await prisma.gallery.update({ where: { id: existing.id }, data: galData });
    } else {
      await prisma.gallery.create({ data: galData });
    }
  }

  // 7. TESTIMONIALS (10 testimonials)
  console.log('[SEEDER] 7. Seeding testimonials (10 testimonials)...');
  const testimonialsData = [
    {
      name: 'Ibu Ratna Pertiwi',
      role: 'Ibu Rumah Tangga',
      location: 'Sungailiat, Bangka',
      comment: 'Sayurannya segar sekali! Dikirim jam 8 pagi, kangkung dan bayam masih ada embun subuhnya. Suami dan anak-anak jadi makin lahap makan sayur.',
      rating: 5,
      avatar: '',
      sortOrder: 1,
      active: true,
    },
    {
      name: 'Dr. Hendra Wijaya',
      role: 'Dokter Spesialis Gizi',
      location: 'Pangkalpinang',
      comment: 'Rekomendasi utama saya untuk pasien yang mencari bahan makanan organik murni di Bangka. Kualitas konsisten dan bebas residu pestisida racun.',
      rating: 5,
      avatar: '',
      sortOrder: 2,
      active: true,
    },
    {
      name: 'Chef Maya Indah',
      role: 'Pemilik Restoran Healthy Eats',
      location: 'Pemali, Bangka',
      comment: 'Kualitas pakcoy dan selada hidroponik TaniCo luar biasa renyah. Sangat membantu meningkatkan standar hidangan di restoran kami.',
      rating: 5,
      avatar: '',
      sortOrder: 3,
      active: true,
    },
    {
      name: 'Bapak Syaiful Rahman',
      role: 'Pelanggan Setia',
      location: 'Pangkalpinang',
      comment: 'Proses pemesanan sangat gampang via WhatsApp maupun website. Pengiriman tepat waktu dan kemasannya sangat rapi serta ramah lingkungan.',
      rating: 5,
      avatar: '',
      sortOrder: 4,
      active: true,
    },
    {
      name: 'Ibu Anita Wijaya',
      role: 'Pemilik Katering Sehat',
      location: 'Sungailiat, Bangka',
      comment: 'Sudah 6 bulan langganan paket hemat mingguan TaniCo. Bahan sup dan tumisan selalu dalam kondisi paling segar.',
      rating: 5,
      avatar: '',
      sortOrder: 5,
      active: true,
    },
    {
      name: 'Rian Kusuma',
      role: 'Fitness & Lifestyle Enthusiast',
      location: 'Pemali, Bangka',
      comment: 'Setiap hari rutin bikin jus bayam merah dan wortel baby dari TaniCo. Rasa manis alaminya bikin nagih dan stamina makin jos.',
      rating: 5,
      avatar: '',
      sortOrder: 6,
      active: true,
    },
    {
      name: 'Ibu Dewi Lestari',
      role: 'Ibu Menyusui & Nutrisi Keluarga',
      location: 'Merawang, Bangka',
      comment: 'Membantu banget pas masa MPASI si kecil! Bayam organik dan brokoli segar TaniCo bikin tenang karena tahu 100% bebas bahan kimia.',
      rating: 5,
      avatar: '',
      sortOrder: 7,
      active: true,
    },
    {
      name: 'Pak Bambang Setiawan',
      role: 'Pemilik Cafe Organik',
      location: 'Pangkalpinang',
      comment: 'Konsistensi ukuran dan kesegaran daun mint serta selada Romaine luar biasa. Mitra yang sangat bisa diandalkan!',
      rating: 5,
      avatar: '',
      sortOrder: 8,
      active: true,
    },
    {
      name: 'Dr. Siska Melati',
      role: 'Ahli Diet & Kesehatan',
      location: 'Belinyu, Bangka',
      comment: 'Sangat bangga ada UMKM lokal Bangka seperti TaniCo yang serius mengedukasi masyarakat tentang pentingnya pangan bebas sintetis.',
      rating: 5,
      avatar: '',
      sortOrder: 9,
      active: true,
    },
    {
      name: 'Ibu Fitriani',
      role: 'Pengusaha Kuliner Lokal',
      location: 'Koba, Bangka Tengah',
      comment: 'Tomat cherry dan cabai rawitnya benar-benar juara pedas dan manis alaminya. Sukses terus untuk seluruh petani TaniCo!',
      rating: 5,
      avatar: '',
      sortOrder: 10,
      active: true,
    },
  ];

  for (const testiData of testimonialsData) {
    const existing = await prisma.testimonial.findFirst({ where: { name: testiData.name } });
    if (existing) {
      await prisma.testimonial.update({ where: { id: existing.id }, data: testiData });
    } else {
      await prisma.testimonial.create({ data: testiData });
    }
  }

  // 8. ARTICLES (10 articles)
  console.log('[SEEDER] 8. Seeding articles (10 articles)...');
  const articlesData = [
    {
      title: '5 Alasan Utama Memilih Sayur Organik Untuk Kesehatan Keluarga',
      slug: '5-alasan-utama-memilih-sayur-organik-untuk-kesehatan-keluarga',
      category: 'Kesehatan',
      author: 'Tim Ahli Nutrisi TaniCo',
      image: '',
      excerpt: 'Menjaga kesehatan keluarga dimulai dari piring makan. Pelajari mengapa sayuran organik bebas pestisida adalah investasi terbaik jangka panjang.',
      content: 'Sayuran organik ditanam tanpa pestisida racun atau pupuk sintetis, menjaga kandungan nutrisi dan vitamin alami tetap utuh. Mengonsumsinya secara rutin membantu menurunkan risiko terpapar residu kimia serta meningkatkan daya tahan tubuh harian.',
      readTime: '4 min baca',
      date: '28 Juli 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Kisah Pak Sukardi: Bertani Hidroponik Berkelanjutan di Pemali',
      slug: 'kisah-pak-sukardi-bertani-hidroponik-berkelanjutan-di-pemali',
      category: 'Kisah Mitra',
      author: 'Humas TaniCo Bangka',
      image: '',
      excerpt: 'Simak perjalanan inspiratif mitra petani TaniCo dalam menerapkan metode budidaya ramah lingkungan demi menghasilkan sayur berkualitas.',
      content: 'Pak Sukardi telah mengelola kebun hidroponik seluas 1.500 m2 di Pemali selama lebih dari 5 tahun. Bersama TaniCo, hasil panen beliau langsung diserap pasar lokal dengan harga adil dan jaminan kesegaran.',
      readTime: '5 min baca',
      date: '15 Juli 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: true,
    },
    {
      title: 'Tips Menyimpan Sayur Segar Agar Tahan Hingga 2 Minggu',
      slug: 'tips-menyimpan-sayur-segar-agar-tahan-hingga-2-minggu',
      category: 'Tips & Trik',
      author: 'Chef Dapur TaniCo',
      image: '',
      excerpt: 'Jangan biarkan sayuran Anda cepat layu. Ikuti panduan praktis metode penyimpan sayur hijau agar tetap renyah dan segar.',
      content: 'Pastikan sayuran dikeringkan sebelum masuk kulkas, bungkus dengan tisu dapur basah atau wadah kedap udara untuk menjaga kelembaban optimal.',
      readTime: '3 min baca',
      date: '10 Juli 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Manfaat Klorofil Organik Bagi Imunitas & Kesehatan Pencernaan',
      slug: 'manfaat-klorofil-organik-bagi-imunitas-dan-kesehatan-pencernaan',
      category: 'Kesehatan',
      author: 'Dr. Hendra Wijaya',
      image: '',
      excerpt: 'Klorofil pada sayuran hijau segar bertindak sebagai zat pembersih racun alami dalam darah dan meningkatkan sistem pertahanan tubuh.',
      content: 'Zat hijau daun organik membantu meregenerasi sel darah merah dan memperlancar metabolisme usus. Mengonsumsi kangkung, bayam, atau pakcoy organik fajar hari membantu menjaga stamina prima.',
      readTime: '4 min baca',
      date: '05 Juli 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Kisah Ibu Maryam: Perempuan Pelopor Pertanian Organik Sungailiat',
      slug: 'kisah-ibu-maryam-perempuan-pelopor-pertanian-organik-sungailiat',
      category: 'Kisah Mitra',
      author: 'Humas TaniCo Bangka',
      image: '',
      excerpt: 'Perjuangan Ibu Maryam memberdayakan ibu-ibu tani lokal Sungailiat untuk memproduksi bayam organik berkualitas tinggi.',
      content: 'Ibu Maryam memulai kebun organik dari pekarangan rumah. Kini kelompok tani binaannya menyuplai ratusan kilogram bayam merah dan hijau segar setiap minggu ke TaniCo.',
      readTime: '6 min baca',
      date: '01 Juli 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: true,
    },
    {
      title: 'Resep Jus Detox Hijau 3 Hari Bebas Gula & Pengawet',
      slug: 'resep-jus-detox-hijau-3-hari-bebas-gula-dan-pengawet',
      category: 'Resep Sehat',
      author: 'Tim Nutrisi TaniCo',
      image: '',
      excerpt: 'Panduan membuat jus hijau rendah kalori yang menyegarkan tubuh dan mengembalikan kebugaran pencernaan Anda.',
      content: 'Campurkan selada hidroponik, seledri, mentimun, dan perasan jeruk nipis. Jus ini membantu membuang penumpukan racun dan mencerahkan kulit.',
      readTime: '3 min baca',
      date: '25 Juni 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Mengapa Sistem Hidroponik DFT Lebih Ramah Lingkungan?',
      slug: 'mengapa-sistem-hidroponik-dft-lebih-ramah-lingkungan',
      category: 'Edukasi Tani',
      author: 'Tim Agronomi TaniCo',
      image: '',
      excerpt: 'Mengenal teknologi aliran nutrisi terukur yang menghemat air hingga 90% dibandingkan metode konvensional.',
      content: 'Sistem Deep Flow Technique (DFT) memungkinkan tanaman tumbuh subur dengan air terukur tanpa merusak struktur tanah lokal.',
      readTime: '5 min baca',
      date: '20 Juni 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Panduan Memilih Sayuran Terbaik untuk MPASI Bayi',
      slug: 'panduan-memilih-sayuran-terbaik-untuk-mpasi-bayi',
      category: 'Kesehatan',
      author: 'Dr. Siska Melati',
      image: '',
      excerpt: 'Ibu muda wajib tahu: Jenis sayuran organik paling aman dan kaya asam folat untuk masa tumbuh kembang bayi.',
      content: 'Wortel baby, bayam merah, dan brokoli kukus adalah pilihan ideal pertama MPASI karena teksturnya mudah dilumatkan dan rasanya manis alami.',
      readTime: '4 min baca',
      date: '15 Juni 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
    {
      title: 'Kisah Pak Gunawan: Dari Lahan Kritis Menjadi Kebun Subur Merawang',
      slug: 'kisah-pak-gunawan-dari-lahan-kritis-menjadi-kebun-subur-merawang',
      category: 'Kisah Mitra',
      author: 'Humas TaniCo Bangka',
      image: '',
      excerpt: 'Bagaimana pupuk kompos organik merehabilitasi tanah bekas tambang menjadi kawasan agrowisata sayur segar.',
      content: 'Pak Gunawan membuktikan bahwa dengan pengolahan tanah yang sabar dan teknik organik murni, lahan bekas dapat kembali produktif dan menghasilkan bahan pangan sehat.',
      readTime: '6 min baca',
      date: '10 Juni 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: true,
    },
    {
      title: 'Pertanian Sirkular Bangka: Mengolah Limbah Organik Menjadi Kompos Super',
      slug: 'pertanian-sirkular-bangka-mengolah-limbah-organik-menjadi-kompos-super',
      category: 'Edukasi Tani',
      author: 'Tim Agronomi TaniCo',
      image: '',
      excerpt: 'Komitmen TaniCo menciptakan rantai pasok nol limbah dengan mendaur ulang seluruh sisa sisa pangkasan sayur.',
      content: 'Sisa tanaman panen diproses menjadi pupuk kompos kaya nutrisi mikro yang digunakan kembali untuk menyuburkan periode tanam berikutnya.',
      readTime: '4 min baca',
      date: '05 Juni 2026',
      status: 'published',
      showOnHomepage: true,
      showOnKisahMitra: false,
    },
  ];

  for (const artData of articlesData) {
    await prisma.article.upsert({
      where: { slug: artData.slug },
      update: artData,
      create: artData,
    });
  }

  // 9. PARTNERS (10 local farmer partners)
  console.log('[SEEDER] 9. Seeding partners (10 local farmer partners)...');
  const partnersData = [
    {
      name: 'Kelompok Tani Makmur Pemali',
      logo: '',
      location: 'Pemali, Bangka',
      description: 'Mitra utama budidaya kangkung, selada, dan pakcoy hidroponik sistem DFT bersih.',
      website: '#',
      sortOrder: 1,
      active: true,
    },
    {
      name: 'Komunitas Organik Bangka',
      logo: '',
      location: 'Sungailiat, Bangka',
      description: 'Penyedia sayuran hijau, bayam, dan umbi-umbian bebas pestisida kimia.',
      website: '#',
      sortOrder: 2,
      active: true,
    },
    {
      name: 'Asosiasi Hidroponik Bangka Belitung',
      logo: '',
      location: 'Pangkalpinang',
      description: 'Pendamping teknologi budidaya hidroponik ramah lingkungan dan standar mutu pangan.',
      website: '#',
      sortOrder: 3,
      active: true,
    },
    {
      name: 'Koperasi Petani Sayur Sungailiat',
      logo: '',
      location: 'Sungailiat, Bangka',
      description: 'Produsen tomat, cabai rawit, dan terong ungu masak pohon alami.',
      website: '#',
      sortOrder: 4,
      active: true,
    },
    {
      name: 'Kebun Bio-Organik Merawang',
      logo: '',
      location: 'Merawang, Bangka',
      description: 'Pengembang pupuk organik lokal dan budidaya brokoli serta kembang kol.',
      website: '#',
      sortOrder: 5,
      active: true,
    },
    {
      name: 'Kelompok Tani Tunas Hijau Belinyu',
      logo: '',
      location: 'Belinyu, Bangka',
      description: 'Sentra produksi sawi pahit, labu siam, dan mentimun organik tradisional.',
      website: '#',
      sortOrder: 6,
      active: true,
    },
    {
      name: 'Farm Hydroponics Pangkalpinang',
      logo: '',
      location: 'Pangkalpinang',
      description: 'Pemasok selada Romaine dan kailan mutu resto untuk katering dan hotel.',
      website: '#',
      sortOrder: 7,
      active: true,
    },
    {
      name: 'Mitra Tani Barokah Koba',
      logo: '',
      location: 'Koba, Bangka Tengah',
      description: 'Spesialis cabai merah keriting dan jagung manis organik bebas pestisida.',
      website: '#',
      sortOrder: 8,
      active: true,
    },
    {
      name: 'Grup Petani Muda Bangka',
      logo: '',
      location: 'Pemali, Bangka',
      description: 'Inovator pertukaran teknologi pertanian presisi dan smart-watering system.',
      website: '#',
      sortOrder: 9,
      active: true,
    },
    {
      name: 'Sentra Organik Bukit Intan',
      logo: '',
      location: 'Pangkalpinang',
      description: 'Kebun herba, daun mint, seledri, dan tanaman obat keluarga (TOGA) segar.',
      website: '#',
      sortOrder: 10,
      active: true,
    },
  ];

  for (const partData of partnersData) {
    const existing = await prisma.partner.findFirst({ where: { name: partData.name } });
    if (existing) {
      await prisma.partner.update({ where: { id: existing.id }, data: partData });
    } else {
      await prisma.partner.create({ data: partData });
    }
  }

  // 10. HERO BANNERS
  console.log('[SEEDER] 10. Seeding hero banners...');
  const heroBannersData = [
    {
      title: 'Panen Segar Subuh Ini, Sampai di Pintu Anda Pagi Ini',
      subtitle: 'Murni Organik & Hidroponik Bebas Pestisida',
      description: 'Nikmati sayuran hijau pilihan langsung dipetik fajar hari dari kebun mitra lokal Bangka. Nutrisi penuh untuk keluarga tercinta.',
      badge: 'TANICO BANGKA',
      buttonText: 'Jelajahi Produk',
      buttonLink: '/produk',
      image: '',
      desktopImage: '',
      mobileImage: '',
      active: true,
      sortOrder: 1,
    },
    {
      title: '100% Bebas Pestisida Kimia & Pupuk Sintetis',
      subtitle: 'Sehat untuk Seluruh Anggota Keluarga',
      description: 'Mendukung keberlanjutan petani lokal Bangka dengan produk ramah lingkungan dan aman dikonsumsi harian.',
      badge: 'SEGAR & ORGANIK',
      buttonText: 'Belanja Sekarang',
      buttonLink: '/produk',
      image: '',
      desktopImage: '',
      mobileImage: '',
      active: true,
      sortOrder: 2,
    },
    {
      title: 'Mendukung Petani Lokal Bangka dengan Harga Adil',
      subtitle: 'Kemitraan Berkelanjutan & Berdaya Saing',
      description: 'Setiap lembar sayur yang Anda beli memberikan dampak langsung pada kesejahteraan keluarga petani di Pemali, Sungailiat, dan Merawang.',
      badge: 'DAMPAL LOKAL',
      buttonText: 'Kisah Mitra Tani',
      buttonLink: '/artikel',
      image: '',
      desktopImage: '',
      mobileImage: '',
      active: true,
      sortOrder: 3,
    },
  ];

  for (const heroData of heroBannersData) {
    const existing = await prisma.heroBanner.findFirst({ where: { title: heroData.title } });
    if (existing) {
      await prisma.heroBanner.update({ where: { id: existing.id }, data: heroData });
    } else {
      await prisma.heroBanner.create({ data: heroData });
    }
  }

  // 10b. HERO BENEFITS (4 benefit cards)
  console.log('[SEEDER] 11. Seeding hero benefits (4 benefit cards)...');
  const heroBenefitsData = [
    {
      value: 'Garansi Kesegaran',
      label: 'Sayuran segar dipanen setiap subuh dan langsung dikirim ke pintu Anda di hari yang sama.',
      image: '',
      sortOrder: 0,
      active: true,
    },
    {
      value: '100% Organik Murni',
      label: 'Bebas pestisida kimia berbahaya, diproduksi berkelanjutan dengan metode selaras alam.',
      image: '',
      sortOrder: 1,
      active: true,
    },
    {
      value: 'Kemitraan Adil',
      label: 'Mendukung pertumbuhan ekonomi berkelanjutan dan harga panen yang adil bagi petani lokal.',
      image: '',
      sortOrder: 2,
      active: true,
    },
    {
      value: 'Layanan Terbaik',
      label: 'Pengemasan higienis, jaminan penggantian produk, dan pelayanan ramah pelanggan.',
      image: '',
      sortOrder: 3,
      active: true,
    },
  ];

  for (let i = 0; i < heroBenefitsData.length; i++) {
    const bData = heroBenefitsData[i];
    const existing = await prisma.heroBenefit.findFirst({ where: { sortOrder: bData.sortOrder } });
    if (existing) {
      await prisma.heroBenefit.update({ where: { id: existing.id }, data: bData });
    } else {
      await prisma.heroBenefit.create({ data: bData });
    }
  }

  // 11. WEBSITE SETTINGS & HOMEPAGE CMS
  console.log('[SEEDER] 12. Seeding website settings and homepage CMS...');
  
  const homepageCMSObj = {
    hero: {
      autoplay: true,
      autoplaySpeed: "5000",
      slides: heroBannersData.map((b, i) => ({
        id: `hero-${i + 1}`,
        badge: b.badge,
        title: b.title,
        subtitle: b.subtitle,
        description: b.description,
        buttonText: b.buttonText,
        buttonLink: b.buttonLink,
        image: '',
        desktopImage: '',
        mobileImage: '',
        background: i === 0 ? '#ECF6ED' : i === 1 ? '#F4F8F5' : '#E8F3EA',
        active: true,
      })),
    },
    about: {
      show: true,
      title: 'TaniCo — Sayur Segar Organik Bangka',
      subtitle: 'Komitmen Murni Kesegaran dari Fajar Hingga Meja Makan',
      description: 'TaniCo hadir sebagai jembatan antara kebun petani lokal di Kabupaten Bangka dengan meja makan keluarga Anda. Sayur dipanen fajar hari dan dikirim langsung pagi itu juga.',
      image: '',
      features: [
        { title: 'Dipetik Fajar Subuh', desc: 'Panen dilakukan jam 04.30 - 06.00 WIB untuk mengunci kesegaran dan klorofil murni.' },
        { title: '100% Bebas Pestisida', desc: 'Menggunakan bahan pengendali hama organik ramah lingkungan.' },
        { title: 'Pengiriman Cepat', desc: 'Sampai di rumah Anda di Bangka pada pagi hari yang sama.' },
      ],
    },
    farmer: {
      show: true,
      title: 'Kisah Mitra Petani Lokal Bangka',
      subtitle: 'Keberlanjutan & Kesejahteraan Bersama Petani Pemali, Sungailiat & Merawang',
      description: 'Setiap ikat sayur yang Anda pesan memberikan apresiasi adil secara langsung kepada petani lokal.',
    },
    benefit: {
      show: true,
      title: 'Mengapa Memilih Sayuran TaniCo?',
      subtitle: 'Jaminan Kualitas Mutlak Hasil Bumi Bangka Belitung',
      list: benefitsList.map((b, i) => ({ id: `b_${i}`, title: b, description: 'Terjamin kesegaran & keamanannya.' })),
    },
    gallery: {
      show: true,
      title: 'Kehidupan di Balik Hasil Panen',
      description: 'Lihat lebih dekat aktivitas para petani lokal Bangka, proses panen, serta perjalanan hasil bumi terbaik hingga sampai ke rumah Anda.',
      limit: 10,
    },
    testimonials: {
      show: true,
      title: 'Ulasan & Kepercayaan Pelanggan',
      subtitle: 'Pengalaman Nyata Keluarga Sehat di Bangka',
      list: testimonialsData,
    },
    partners: {
      show: true,
      title: 'Mitra Petani & Komunitas Lokal',
      subtitle: 'Sinergi Bersama Membangun Ketahanan Pangan Sehat Bangka',
      list: partnersData,
      logos: partnersData,
    },
    banner: {
      show: true,
      title: 'Garansi Kesegaran 100%',
      subtitle: 'Apabila sayuran yang diterima tidak segar atau layu, kami ganti gratis pada pengiriman berikutnya tanpa syarat.',
      buttonText: 'Belanja Sayur Segar Now',
      buttonLink: '/produk',
      image: '',
    },
    cta: {
      show: true,
      title: 'Siap Menikmati Sayuran Segar Hari Ini?',
      subtitle: 'Pesan sebelum pukul 20.00 WIB untuk dipanen esok subuh dan dikirim ke pintu Anda.',
      buttonText: 'Mulai Belanja Sekarang',
      buttonLink: '/produk',
    },
  };

  // 12. ACTIVITY LOG
  console.log('[SEEDER] 13. Creating activity log entry...');
  await prisma.activityLog.create({
    data: {
      adminName: 'Administrator TaniCo',
      action: 'Initialized database seeder with complete TaniCo data (30 products, 10 gallery items, 10 testimonials, 10 articles, 10 partners).',
    },
  });

  console.log('');
  console.log('================================================================================');
  console.log('TANICO DATABASE SEEDING COMPLETED SUCCESSFULLY');
  console.log('================================================================================');
  console.log(`   - Super Admin: admin@tanico.id`);
  console.log(`   - Password   : ${plainPassword}`);
  console.log(`   - Total Products    : 30 products`);
  console.log(`   - Total Categories  : 6 categories`);
  console.log(`   - Total Gallery     : 10 photos`);
  console.log(`   - Total Testimonials: 10 reviews`);
  console.log(`   - Total Articles    : 10 articles`);
  console.log(`   - Total Partners    : 10 farmer partners`);
  console.log(`   - CMS & Settings    : Pre-configured and ready to use`);
  console.log('================================================================================');
  console.log('');
}

main()
  .catch((e) => {
    console.error('[SEEDER] Error during database seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });