export const LIMITS = {
  MAX_CART_ITEMS: 50,
  MAX_WISHLIST_ITEMS: 100,
  MAX_ITEM_QUANTITY: 99,
  DEFAULT_PAGE_SIZE: 12
};

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

export const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED'
};
